### ISSUE TITLE
Procedures of class Timeseries are slow

### ISSUE THREAD

**Issue by rozos** [openmeteo/pthelma#27]
Procedures \__setitem__, \__getitem__, up and next are not fast enough to handle long timeseries. The seconds spent per call in an Intel(R) Pentium(R) Dual  CPU  E2200  @ 2.20GHz are (see output of python profiler at the end):

    \__setitem__	2.00E-05
    \__getitem__	1.18E-05
    up             	8.30E-06
    next          	7.31E-06

Suppose a 1000 years model simulation with daily timestep. Suppose that the model returns 50 timeseries. This makes 365\*1000\*50 calls of each procedure. The following gives the total minutes spent in each one:

    \__setitem__	6.07E+00
    up          	2.53E+00
    next        	2.22E+00

In total more than 10 minutes only to store the timeseries that the model returns!

OUTPUT OF PYTHON PROFILER

    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    7889184  157.447    0.000  302.060    0.000 /home/rozos/local/dev/pyuwot/pthelma/timeseries.py:348(\__setitem__)
    8035276   66.718    0.000  101.583    0.000 /home/rozos/local/dev/pyuwot/pthelma/timeseries.py:150(up)
    8035276   58.722    0.000  175.565    0.000 /home/rozos/local/dev/pyuwot/pthelma/timeseries.py:207(next)
     292192    3.435    0.000    6.734    0.000 /home/rozos/local/dev/pyuwot/pthelma timeseries.py:380(\__getitem__)

**Comment by aptiko** [comment]
I am surprised they are so slow. Thanks for the report. However, it is unlikely that this will be fixed any time soon, so I am closing the issue. At some point in the future (when the appropriate funding is secured), pthelma will be changed to use pandas instead of dickinson, and this will solve many problems. It may be a good idea if you use pandas instead of pthelma for your application (come to borrow the book if you are interested).
